engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
   paths:
   - server/**
   - config/**
   - "**.js"
exclude_paths:
- node_modules/**/*
- server/tests/**
