language: node_js
node_js:
  - "node"
  - "iojs"
  - "7"
  - "6"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - yarn test:check-coverage
after_script:
  - yarn report-coverage
