language: node_js
node_js:
  - "node"
  - "7"
  - "6"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
before_install:
  - cp .env.default .env
script:
  - yarn test:check-coverage
after_script:
  - yarn report-coverage
  - bithound check git@github.com:$TRAVIS_REPO_SLUG.git
