language: node_js
node_js:
  - "node"
  - "7"
  - "6"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
before_install:
  - git fetch --unshallow
  - cp .env.default .env
script:
  - yarn test:check-coverage
  - /bin lint-commits.sh
  - ./node_modules/.bin/commitlint --from=$TRAVIS_COMMIT
after_script:
  - yarn report-coverage
  - bithound check git@github.com:$TRAVIS_REPO_SLUG.git
